DROP DATABASE IF EXISTS BOOKS; 

CREATE DATABASE BOOKS;

USE BOOKS;

CREATE TABLE Main (
    ID int not null auto_increment,
    AUTHOR VARCHAR(30) NOT NULL,
    Genres VARCHAR(15) NOT NULL,
    PUBLISHED_YEAR YEAR(4) NOT NULL,
    BOOK_LENGTH VARCHAR(10) NOT NULL,
    SUMMARY TEXT NULL,
	URL VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID)
)
;

 CREATE TABLE Userlogin 
(

  ID INT NOT NULL auto_increment, 
  EMAIL_ADDRESS VARCHAR(50) NOT NULL,
  P_WORD VARCHAR(40) NOT NULL,
  STATUS ENUM,
  PRIMARY KEY (ID)

);  


INSERT INTO userlogin (EMAIL_ADDRESS,P_WORD)
VALUES('user1@gmail.com','test12345');
 
INSERT INTO userlogin (EMAIL_ADDRESS,P_WORD)
VALUES('user2@gmail.com','test123');

SELECT *
FROM USERLOGIN;

